# Generated by Django 6.0.7 on 2026-07-09 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_a', models.FileField(upload_to='uploads/')),
                ('file_b', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('differences_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
