# Generated by Django 6.0.7 on 2026-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
    ]
